version: '2.1'

services:
  mysql:
    container_name: mysql
    image: docker.pkg.github.com/b1412/docker-mysql/docker-mysql:23
    ports:
      - "3306:3306"
    volumes:
      - local-mysql-data:/var/lib/mysql
    healthcheck:
      #test: "mysqladmin ping --silent"
      interval: 5s
      timeout: 60s
      retries: 10
  redis:
    container_name: redis
    image: redis:5.0.6
    command: --save 100 60 --appendonly yes
    volumes:
      - local-redis-data:/persistent
  kotlin-cannon-api:
    container_name: kotlin-cannon
    image: docker.pkg.github.com/b1412/kotlin-cannon/kotlin-cannon-api:129
    links:
      - mysql
      - redis
  nginx:
    container_name: nginx
    image: docker.pkg.github.com/b1412/dev-nginx/dev-nginx:5
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443

volumes:
  local-mysql-data:
    driver: local
  local-redis-data:
    driver: local
