version: '2.1'

services:
  mysql:
    container_name: mysql
    image: docker.pkg.github.com/b1412/docker-mysql/docker-mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - local-mysql-data:/var/lib/mysql
    healthcheck:
      interval: 5s
      timeout: 60s
      retries: 10
  redis:
    container_name: redis
    image: redis:5.0.6
    ports:
      - "6379:6379"
    command: --save 100 60 --appendonly yes
    volumes:
      - local-redis-data:/persistent


  permission-api:
    container_name: permission-api
    image: docker.pkg.github.com/b1412/permission-api/permission-api:latest
    links:
      - mysql
      - redis

  permission-ui:
    container_name: permission-ui
    image: docker.pkg.github.com/b1412/permission-ui/permission-ui:latest

  nginx:
    container_name: nginx
    image: docker.pkg.github.com/b1412/dev-nginx/dev-nginx:latest
    ports:
      - 80:80
volumes:
  local-mysql-data:
    driver: local
  local-redis-data:
    driver: local
