version: '2.1'

services:
  mysql:
    container_name: cannon-mysql
    image: cannon-mysql:latest
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - cannon-mysql-data:/var/lib/mysql
  kotlin-cannon:
    container_name: kotlin-cannon
    image: kotlin-cannon:latest
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  cannon-mysql-data:
    driver: local
