version: '2.1'

services:
  mysql:
    container_name: docker-mysql
    image: b1412/docker-mysql:3
    ports:
      - "3306:3306"
    volumes:
      - local-mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: 5s
      timeout: 60s
      retries: 10
  kotlin-cannon:
    container_name: kotlin-cannon
    image: b1412/kotlin-cannon:107
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  local-mysql-data:
    driver: local
