#!/usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source "$DIR/scripts/_common"


info "Checking memory"
DOCKER_MEM=`docker info -f '{{.MemTotal}}'`
MEM_STATUS=`echo $DOCKER_MEM'>2000000000' | bc -l -q`
if [[ $MEM_STATUS -ne 1 ]]; then
  fail "You do not have enough memory allocated to Docker! You should allocate at least 2GB"
else
  ok "Memory looks good"
fi

info "Checking local alias"
set +e
ifconfig lo0 | grep -F "10.100.10.1"
if [[ $? -ne 0 ]]; then
  info "Setting local alias, you will be prompted for your sudo password"
  sudo ifconfig lo0 alias 10.100.10.1/24
  info "Alias added with IP 10.100.10.1"
fi
set -e

#./scripts/add_host.sh

echo "All done"

